# Language of the application
language: node_js

# Version of nodejs (and npm) to be installed
node_js:
    - "10.13.0"

# Only run any changes to master and develop branches
branches:
    only:
        - master
        - develop

# Only clone the latest code
git:
    depth: false

# Run commands in host machine in non-sudo
sudo: false

# Caches the dependencies and only install/update new dependencies
cache: npm

# Script for TravisCI to run
script:
    # Run test scripts
    - npm run test
    # Run linting
    # - npm run lint
