// flow-typed signature: c427d0e6b7d3896b94c2cb28caadb013
// flow-typed version: <<STUB>>/chai-string_v^1.5.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai-string'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai-string' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chai-string/chai-string' {
  declare module.exports: any;
}

declare module 'chai-string/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chai-string/chai-string.js' {
  declare module.exports: $Exports<'chai-string/chai-string'>;
}
declare module 'chai-string/test/test.js' {
  declare module.exports: $Exports<'chai-string/test/test'>;
}
