// flow-typed signature: 51eb4ddb2212216f0d2b2f6cdf60191f
// flow-typed version: <<STUB>>/outdent_v^0.7.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'outdent'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'outdent' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'outdent/lib-module/index' {
  declare module.exports: any;
}

declare module 'outdent/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'outdent/lib-module/index.js' {
  declare module.exports: $Exports<'outdent/lib-module/index'>;
}
declare module 'outdent/lib/index.js' {
  declare module.exports: $Exports<'outdent/lib/index'>;
}
