// flow-typed signature: fee9bc82a2dfa0233c5a19d91aaae666
// flow-typed version: <<STUB>>/telegraf_v^3.27.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'telegraf'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'telegraf' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'telegraf/composer' {
  declare module.exports: any;
}

declare module 'telegraf/core/context' {
  declare module.exports: any;
}

declare module 'telegraf/core/network/client' {
  declare module.exports: any;
}

declare module 'telegraf/core/network/error' {
  declare module.exports: any;
}

declare module 'telegraf/core/network/multipart-stream' {
  declare module.exports: any;
}

declare module 'telegraf/core/network/webhook' {
  declare module.exports: any;
}

declare module 'telegraf/core/replicators' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/custom-router-bot' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/deeplink-bot' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/echo-bot' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/example-bot' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/express-webhook-bot' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/fastify-webhook-bot' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/game-bot' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/inline-bot' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/keyboard-bot' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/koa-webhook-bot' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/live-location-bot' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/media-bot' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/scenes-bot' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/self-cleaning-scenes' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/shop-bot' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/webhook-bot' {
  declare module.exports: any;
}

declare module 'telegraf/docs/examples/wizard-bot' {
  declare module.exports: any;
}

declare module 'telegraf/extra' {
  declare module.exports: any;
}

declare module 'telegraf/markup' {
  declare module.exports: any;
}

declare module 'telegraf/router' {
  declare module.exports: any;
}

declare module 'telegraf/scenes/base' {
  declare module.exports: any;
}

declare module 'telegraf/scenes/context' {
  declare module.exports: any;
}

declare module 'telegraf/scenes/wizard/context' {
  declare module.exports: any;
}

declare module 'telegraf/scenes/wizard/index' {
  declare module.exports: any;
}

declare module 'telegraf/session' {
  declare module.exports: any;
}

declare module 'telegraf/stage' {
  declare module.exports: any;
}

declare module 'telegraf/telegraf' {
  declare module.exports: any;
}

declare module 'telegraf/telegram' {
  declare module.exports: any;
}

declare module 'telegraf/test/composer' {
  declare module.exports: any;
}

declare module 'telegraf/test/extra' {
  declare module.exports: any;
}

declare module 'telegraf/test/markup' {
  declare module.exports: any;
}

declare module 'telegraf/test/telegraf' {
  declare module.exports: any;
}

// Filename aliases
declare module 'telegraf/composer.js' {
  declare module.exports: $Exports<'telegraf/composer'>;
}
declare module 'telegraf/core/context.js' {
  declare module.exports: $Exports<'telegraf/core/context'>;
}
declare module 'telegraf/core/network/client.js' {
  declare module.exports: $Exports<'telegraf/core/network/client'>;
}
declare module 'telegraf/core/network/error.js' {
  declare module.exports: $Exports<'telegraf/core/network/error'>;
}
declare module 'telegraf/core/network/multipart-stream.js' {
  declare module.exports: $Exports<'telegraf/core/network/multipart-stream'>;
}
declare module 'telegraf/core/network/webhook.js' {
  declare module.exports: $Exports<'telegraf/core/network/webhook'>;
}
declare module 'telegraf/core/replicators.js' {
  declare module.exports: $Exports<'telegraf/core/replicators'>;
}
declare module 'telegraf/docs/examples/custom-router-bot.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/custom-router-bot'>;
}
declare module 'telegraf/docs/examples/deeplink-bot.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/deeplink-bot'>;
}
declare module 'telegraf/docs/examples/echo-bot.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/echo-bot'>;
}
declare module 'telegraf/docs/examples/example-bot.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/example-bot'>;
}
declare module 'telegraf/docs/examples/express-webhook-bot.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/express-webhook-bot'>;
}
declare module 'telegraf/docs/examples/fastify-webhook-bot.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/fastify-webhook-bot'>;
}
declare module 'telegraf/docs/examples/game-bot.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/game-bot'>;
}
declare module 'telegraf/docs/examples/inline-bot.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/inline-bot'>;
}
declare module 'telegraf/docs/examples/keyboard-bot.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/keyboard-bot'>;
}
declare module 'telegraf/docs/examples/koa-webhook-bot.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/koa-webhook-bot'>;
}
declare module 'telegraf/docs/examples/live-location-bot.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/live-location-bot'>;
}
declare module 'telegraf/docs/examples/media-bot.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/media-bot'>;
}
declare module 'telegraf/docs/examples/scenes-bot.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/scenes-bot'>;
}
declare module 'telegraf/docs/examples/self-cleaning-scenes.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/self-cleaning-scenes'>;
}
declare module 'telegraf/docs/examples/shop-bot.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/shop-bot'>;
}
declare module 'telegraf/docs/examples/webhook-bot.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/webhook-bot'>;
}
declare module 'telegraf/docs/examples/wizard-bot.js' {
  declare module.exports: $Exports<'telegraf/docs/examples/wizard-bot'>;
}
declare module 'telegraf/extra.js' {
  declare module.exports: $Exports<'telegraf/extra'>;
}
declare module 'telegraf/markup.js' {
  declare module.exports: $Exports<'telegraf/markup'>;
}
declare module 'telegraf/router.js' {
  declare module.exports: $Exports<'telegraf/router'>;
}
declare module 'telegraf/scenes/base.js' {
  declare module.exports: $Exports<'telegraf/scenes/base'>;
}
declare module 'telegraf/scenes/context.js' {
  declare module.exports: $Exports<'telegraf/scenes/context'>;
}
declare module 'telegraf/scenes/wizard/context.js' {
  declare module.exports: $Exports<'telegraf/scenes/wizard/context'>;
}
declare module 'telegraf/scenes/wizard/index.js' {
  declare module.exports: $Exports<'telegraf/scenes/wizard/index'>;
}
declare module 'telegraf/session.js' {
  declare module.exports: $Exports<'telegraf/session'>;
}
declare module 'telegraf/stage.js' {
  declare module.exports: $Exports<'telegraf/stage'>;
}
declare module 'telegraf/telegraf.js' {
  declare module.exports: $Exports<'telegraf/telegraf'>;
}
declare module 'telegraf/telegram.js' {
  declare module.exports: $Exports<'telegraf/telegram'>;
}
declare module 'telegraf/test/composer.js' {
  declare module.exports: $Exports<'telegraf/test/composer'>;
}
declare module 'telegraf/test/extra.js' {
  declare module.exports: $Exports<'telegraf/test/extra'>;
}
declare module 'telegraf/test/markup.js' {
  declare module.exports: $Exports<'telegraf/test/markup'>;
}
declare module 'telegraf/test/telegraf.js' {
  declare module.exports: $Exports<'telegraf/test/telegraf'>;
}
